# Generated by Django 4.2.21 on 2025-07-26 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_service_alter_user_email'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['id']},
        ),
        migrations.AlterField(
            model_name='service',
            name='servicelength',
            field=models.DurationField(help_text='Duration in HH:MM:SS'),
        ),
    ]
