# Generated by Django 4.2.21 on 2025-07-26 20:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_user_options_alter_service_servicelength'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='stylist',
            field=models.ManyToManyField(related_name='services', to=settings.AUTH_USER_MODEL),
        ),
    ]
